//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeightChecking.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ed3YbBgz3fF3bb/osXwqYNhSCfyKvNWvXPUgvQLnsbz+Nd6Vj/7Bp8rlvWbE/zlBsqiGfzls0FozxdSpL" +
            "EGyIYk/FpLk0PUEB0owITx4e7QWtAs6hhG9O20ffz+nroHV3b//mZ91MP5kAywrsmMsnt2//5mfdTD+Z" +
            "FycX6i+aqjOePbB/5XtS54TqvGoMQ6uZs5JoyLjxtFaOXCkfgRc3OCVgB+kkBmL")]
        public string conString {
            get {
                return ((string)(this["conString"]));
            }
            set {
                this["conString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("192.168.80.3")]
        public string ipConveyor {
            get {
                return ((string)(this["ipConveyor"]));
            }
            set {
                this["ipConveyor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ed3YbBgz3fF3bb/osXwqYNhSCfyKvNWvXPUgvQLnsbxhiBYExpE31Zqka9VTJreKXnvPXqdo2TaQPGxYv" +
            "jIEfeJvW5J47WBVFrQLOoYRvTttH38/p66B1d2//5mfdTD+ZAMsK7JjLJ7dv/+Zn3Uw/mRcnF+ovmqoz" +
            "nj2wf+V7UueE6rxqDEOrmbOSaMi48bRWjlwpH4EXNzglYAfpJAZiw==")]
        public string conStringWL {
            get {
                return ((string)(this["conStringWL"]));
            }
            set {
                this["conStringWL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public string UnitScale {
            get {
                return ((string)(this["UnitScale"]));
            }
            set {
                this["UnitScale"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("COM2")]
        public string ComPortScale {
            get {
                return ((string)(this["ComPortScale"]));
            }
            set {
                this["ComPortScale"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\10.40.10.9\\Public$\\98_Public_Share\\99_Shared\\05_IT\\01_Update\\21- IDCScaleSystem" +
            "\\update.xml")]
        public string UpdatePath {
            get {
                return ((string)(this["UpdatePath"]));
            }
            set {
                this["UpdatePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsScale {
            get {
                return ((bool)(this["IsScale"]));
            }
            set {
                this["IsScale"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsCounter {
            get {
                return ((bool)(this["IsCounter"]));
            }
            set {
                this["IsCounter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Station {
            get {
                return ((int)(this["Station"]));
            }
            set {
                this["Station"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int AfterPrinting {
            get {
                return ((int)(this["AfterPrinting"]));
            }
            set {
                this["AfterPrinting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("COM4")]
        public string PrintComPort {
            get {
                return ((string)(this["PrintComPort"]));
            }
            set {
                this["PrintComPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int ScannerIdMetal {
            get {
                return ((int)(this["ScannerIdMetal"]));
            }
            set {
                this["ScannerIdMetal"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int ScannerIdWeight {
            get {
                return ((int)(this["ScannerIdWeight"]));
            }
            set {
                this["ScannerIdWeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int ScannerIdPrint {
            get {
                return ((int)(this["ScannerIdPrint"]));
            }
            set {
                this["ScannerIdPrint"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public double TimeCheckQrMetal {
            get {
                return ((double)(this["TimeCheckQrMetal"]));
            }
            set {
                this["TimeCheckQrMetal"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public double TimeCheckQrScale {
            get {
                return ((double)(this["TimeCheckQrScale"]));
            }
            set {
                this["TimeCheckQrScale"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsTest {
            get {
                return ((bool)(this["IsTest"]));
            }
            set {
                this["IsTest"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ed3YbBgz3fF3bb/osXwqYNhSCfyKvNWvXPUgvQLnsbz+Nd6Vj/7Bp3JpDzU1SquQf9r/UjvioXIcrdYeK" +
            "JIBZxfUIaWnODCfVyoZD4vtKfTY2bzuwo+x9IWaUwNDM8sXy0vvVfwBcTaxNaqOPWxs7wJ2VL5tVKN6N" +
            "Xz6gB+a8K0JokfzGUFtGBP4RKiPCgVqqhImSXhPA27fwcNR/ExwoYestgqmQS8+")]
        public string conStringTest {
            get {
                return ((string)(this["conStringTest"]));
            }
            set {
                this["conStringTest"] = value;
            }
        }
    }
}
